#!/usr/bin/env bash
set -euo pipefail

if [[ $(qs -c omadora ipc call notifications isSilenced 2>/dev/null) == true ]]; then
  echo '{"text": "󰂛", "tooltip": "Notifications silenced", "class": "active"}'
else
  echo '{"text": ""}'
fi
