#!/bin/bash

# Toggle notification do-not-disturb mode

if [[ $(qs -c omadora ipc call notifications toggleSilenced) == true ]]; then
  notify-send -u low "󰂛    Silenced notifications"
else
  notify-send -u low "󰂚    Enabled notifications"
fi

"$(dirname "${BASH_SOURCE[0]}")/omadora-bar-refresh" notification-silencing
