#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Overwrite the user configs for the top bar (Waybar and Quickshell) with the defaults and restart it.

omadora_run omadora-refresh-config waybar/config.jsonc
omadora_run omadora-refresh-config waybar/style.css
for file in "$OMADORA_ROOT"/config/quickshell/omadora/*; do
  omadora_run omadora-refresh-config "quickshell/omadora/${file##*/}"
done
omadora_run omadora-restart-waybar
