#!/usr/bin/env bash
set -euo pipefail

# Remove FIDO2 authentication from sudo and polkit

echo -e "\e[32mRemoving FIDO2 device from authentication.\e[0m"

sudo -v || exit 1

echo
echo -e "\e[32mDisabling U2F authentication...\e[0m"
sudo sed -i '/pam_u2f.so/d' /etc/pam.d/sudo
echo "Done."

echo
echo -e "\e[32mRemoving U2F keys...\e[0m"
key_dir="$HOME"/.config/Yubico
if [[ -d $key_dir ]]; then
  rm -rf "$key_dir"
fi
echo "Done."

echo
if gum confirm "Remove related packages?"; then
  echo
  echo -e "\e[32mRemoving installed packages...\e[0m"
  sudo pacman -Rns --noconfirm pam-u2f || true
  echo "Done."
  echo
fi

echo -e "\e[32mFIDO2 U2F authentication removed.\e[0m"
