#!/bin/bash

# Dismiss a notification on the basis of its summary. Used by the first-run notifications to dismiss them after clicking for action.

if (($# == 0)); then
  echo "Usage: omadora-notification-dismiss <summary>"
  exit 1
fi

qs -c omadora ipc call notifications dismissBySummary "$1"
