#!/bin/bash

# Toggle notification do-not-disturb mode

makoctl mode -t do-not-disturb

if makoctl mode | grep -q 'do-not-disturb'; then
  notify-send -u low "󰂛    Silenced notifications"
else
  notify-send -u low "󰂚    Enabled notifications"
fi

"$(dirname "${BASH_SOURCE[0]}")/omadora-bar-refresh" notification-silencing
